#index:
#    path: /
#    controller: App\Controller\DefaultController::index

profil:
  path: /profil/{username}
  controller: App\Controller\ProfilController::index
  defaults:
    username: Invite
